const express = require("express");
const router = express.Router();
const authRoute = require("./auth/authRoute");
const blockSeatRoute = require("./api/blockSeatRoute");
const branchRoute = require("./api/branchRoute");
const cinemaRoute = require("./api/cinemaRoute");
const comboItemRoute = require("./api/comboItemRoute");
const comboRoute = require("./api/comboRoute");
const foodAndDrinkRoute = require("./api/foodAndDrinkRoute");
const genreRoute = require("./api/genreRoute");
const movieGenreRoute = require("./api/movieGenreRoute");
const movieRoute = require("./api/movieRoute");
const actorRoute = require("./api/actorRoute");
const movieActorRoute = require("./api/movieActorRoute");
const producerRoute = require("./api/producerRoute");
const movieProducerRoute = require("./api/movieProducerRoute");
const directorRoute = require("./api/directorRoute");
const orderRoute = require("./api/orderRoute");
const paymentSettingRoute = require("./api/paymentSettingRoute");
const priceSettingRoute = require("./api/priceSettingRoute");
const promotionRoute = require("./api/promotionRouter");
const reviewRoute = require("./api/reviewRoute");
const roomRoute = require("./api/roomRoute");
const seatRoute = require("./api/seatRoute");
const seatStatusRoute = require("./api/seatStatusRoute");
const showtimeRoute = require("./api/showtimeRoute");
const ticketRoute = require("./api/ticketRoute");
const ticketStatusRoute = require("./api/ticketStatusRoute");
const userRoute = require("./api/userRoute");
const seatTypeRoute = require("./api/seatTypeRoute");
const paymenRoute = require("./api/PayMomoRoute");
const holidayDateRoute = require("./api/holidayDateRoute");
const qrRoute = require("./api/qrRoute");
const vnpayTestRoutes = require('./api/vnpayTestRoutes');
const chatbotRoute = require('./api/chatbotRoute');
const chatbottestRoute = require('./api/chatboxtestRoute');
const postRoute = require('./api/postRoute');

// Đăng ký các route vào router
router.use("/auth", authRoute);
router.use("/blockSeat", blockSeatRoute);
router.use("/branch", branchRoute);
router.use("/actor", actorRoute);
router.use("/movieActor", movieActorRoute);
router.use("/cinema", cinemaRoute);
router.use("/comboItem", comboItemRoute);
router.use("/combo", comboRoute);
router.use("/foodAndDrink", foodAndDrinkRoute);
router.use("/genre", genreRoute);
router.use("/movieGenre", movieGenreRoute);
router.use("/movie", movieRoute);
router.use("/producer", producerRoute);
router.use("/movieProducer", movieProducerRoute);
router.use("/director", directorRoute);
router.use("/order", orderRoute);
router.use("/paymentSetting", paymentSettingRoute);
router.use("/priceSetting", priceSettingRoute);
router.use("/promotion", promotionRoute);
router.use("/review", reviewRoute);
router.use("/room", roomRoute);
router.use("/seat", seatRoute);
router.use("/seatType", seatTypeRoute);
router.use("/seatStatus", seatStatusRoute);
router.use("/showtime", showtimeRoute);
router.use("/ticket", ticketRoute);
router.use("/ticketStatus", ticketStatusRoute);
router.use("/momo", paymenRoute);
router.use("/user", userRoute);
router.use("/holidayDate", holidayDateRoute);
router.use("/qr", qrRoute);
router.use("/chatbot", chatbotRoute);
router.use("/chatbottest", chatbottestRoute);
router.use("/post", postRoute);

// VNPay Test Routes
router.use('/test-vnpay', vnpayTestRoutes);

module.exports = router;
